# ----------------------------------------
# spring boot yaml
# spring boot 配置文件
# ----------------------------------------
spring.application:
# IDENTITY
  name: rubbish-web

# LOGGING
#  logging:
#    config: classpath:logback.xml

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
spring.http.encoding:
  charset: UTF-8

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server.tomcat:
  uri-encoding: UTF-8

# ----------------------------------------
# DATA PROPERTIES
# ----------------------------------------

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource:
    name: ${datasource.name}
    url:  ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    initial-size: 20
    max-idle: 5
    max-active: 100
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
#    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 10
    remove-abandoned: true
    remove-abandoned-timeout: 180
    log-abandoned: true
    filters: false
    connectionProperties:
      druid.stat.mergeSql: true
      druid.stat.slowSqlMillis: 5000
    useGlobalDataSourceStat: true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis-plu_config
mybatis-plus:
  mapper-locations: classpath:/sqlmap/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.richeninfo.rubbish.entity.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

